# Generated by Django 2.2.4 on 2019-08-12 15:46

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]', null=True, verbose_name='Page blocks')),
            ],
        ),
    ]
